sudo: required

services:
  - docker

env:
  global:
    - secure: "A3Y+F9XfW9u0gSRs3Rx6hjB64y+t/5q2olo4i+Gq/0itj8K+xNApMxpiE4OtOKpUkw24tajP41+aGxE4DkPMTM648oxLjo4Wxzo+6uHsdM4U2okkC0dO7k6LLOlIg1z2/e67cuLWcq6Y/0xKt0BAgRpCgi0W1QZB0HZbfjUhPMc2naipAdRKdV9shL9Aw54VTo6+JQy22FqSJkY2wEphKXw2eyaF3ut1wcrQIMlC9Qe8dSq7uyowrYor+zxd2EowglixUWSDsCFGmd6SJTcYEGSJX5uZeKRjFcP3UuILTEAmcvzeiGV2VSemKicQI436WXLp4QTuNvSzmqUl6wgwfxNxMBaLXbId/ojzSiZnxLZ0M4Bf89HYNvdgCPoK0p4/KcjX9iAzxcsP2U+Wt/VzYl1okCc62XqcBzoHbKK+xrZtXoCdpSNcMYsKp784/HUaDExTSRaWnmDYI/0P/ChJSBNcK4/MSpFnq/ycqNp6mAKQ0yPkr/0YkXcMv12GfpFeWuFIc01Y61xoZRPrIockU1zufYIANP5QUPnAElyEfPXNAmNp6RLo1FfAnl6oD1yjcESeon8CFyvH+mYBu89Y1oZq/gIe3pMuKrfxA9rwm3OuC0XUR2dpMB2RTLthy3yJUTSoVhJeYjhNWfoJRN7Mo8jmO1vZpYgcgBDA7JSQ1O4="
    - secure: "UuXWThgpKSnsclMrbIl1H3osqeh2n6owR4jvRwlKJbcYkelbuyqhWNs17nThOkQGJdQD3/PCmChNKpJ3CrPG9oUKmKKKY5s3iVK9d6l8RDgBetXWI20dGkuKQYOSODKHnl9cTboPvJ2CidcdFw3DXjvd5hsjmnwte7a1qfT9qts7eoCTxOKhU7pflTn6LfXQ4q/92JupM2euS4jMNezgfZA6/TqIjGRNNmCj+CzzgATnI6xJZaPCn2ewziWE43FKmijyaboAJV67+IXxUvlvHeE3ZBT18iM2x7QhpksZ43fx2mNmXXV/ukMvORIMJD/r50zhxUCLqwlwes/pnZboO2oWeCa9HpHUBRWFdo3a69JIzexHWkZ6/ExqSrN6whgNddbH/f5kkjq9EE3BUKoYdl4wGtwgqrkYcf8SK5TFpJOpkmMDHdM23a48qjSoDOUxgnv+/wXIc9ohKzuMZ5RPaDzxqsPMg8lLx0NDF25oA4jgOnZa7ya64JRdvh6NPjKTC23u0J6xaELhFk0U6WAnEYPxtTMPIAA1gEJrcTMwcRycpwjm1JQT+/xv8QEbPVTQbE4mcfAdGZp6uVTz5U3e30xn5OPL8m/DsJPEv3dDq6BQQVyBMAnCVw3vjNGVIyChzD5eHPb6imfBtMQEFrPWlr2rQ06ap0g0rMZGey3d9OA="

  matrix:
    - LATEST=1 TERRAFORM_VERSION=0.11.11 TERRAFORM_SHA256SUM=94504f4a67bad612b5c8e3a4b7ce6ca2772b3c1559630dfd71e9c519e3d6149c
    - LATEST=0 TERRAFORM_VERSION=0.10.8 TERRAFORM_SHA256SUM=b786c0cf936e24145fad632efd0fe48c831558cc9e43c071fffd93f35e3150db
    - LATEST=0 TERRAFORM_VERSION=0.9.11 TERRAFORM_SHA256SUM=804d31cfa5fee5c2b1bff7816b64f0e26b1d766ac347c67091adccc2626e16f3
    - LATEST=0 TERRAFORM_VERSION=0.8.8 TERRAFORM_SHA256SUM=403d65b8a728b8dffcdd829262b57949bce9748b91f2e82dfd6d61692236b376

script:
  - bash docker-build.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images
