sudo: required

services:
  - docker

env:
  global:
    - secure: "ZVhPfJxeXolNPryBuRX/bbZnj+TffDYUZo/6BmIAGI1e9OCpUe4THy5Gu8qjr22FMw8fSG/YMkEmd+UPbqeq8nvw2q2iKeCzKT49F87+MEJTlkduvjb7Q6AKAKJV4SvHy/iAym/KaRg4Q+Z08CYf4UFBFFj0ca/djgH9DgBV44XPcUnYLTk9bsUdddwBBBh9TiOlKhOcGoSuX9HyNKeLDQKlxiqKVat+A8lFY56mHAhXn269nMe+ZrzuaUskq0XQ0fX1Ib8ivIQymNTvglezy69/2EjEfGuBBhEoq8luMHLSb5khs1j2CpBJXQ8/8s419mzxDvsDr8CF8KxsUOmhGxskUsUY2Jp/56SgD5ubfJ6GhW30asvjB8wiOJ5rCNrCho5CyYXHIIDLxNtW0rIgLRzpArlsDfnXqVm1u7huF1hZgb6RmL8fuf1mvVn0AVfSVuvIZBFMnmauSQpVGYF1Wa825RPQH/mwEhBo36KclPBJL8xm2Udz7gA7lMUMbM+Z8XwNrwA28K95UF7SV1wyJyBxoiI7Nz6DC5g6EPLtr6kOTtePaFdu5aM5aGzZEGD1zAYKE6igjOzNTHbOsHLFo+fO05oE75/0N97NUWiUVAtKNFjTlmF6wevWy0rKVvPWiduqcuGAOyA+aQcwLKGehH5ckHOU3wp7bCXFa21VO/0="
    - secure: "iOSOyGjMzppONkPqa74I91wt7tC9kJGMLd1tG/2+GDy0SbkPWjuax7SZ8fCfnSPnYGtNcFy701Po0Rtv+Jdn7fCX4lMv75hZYpF6EKncmHZad9lSYPYb4mGD/TYw7Y53W++zfOZRBf4Zjo8xigk3Jgsmte7kX4MR/6nk54l42W6/kdijzBTqI1xzjU9jDPB5BYB6eIIfS87LZahBWtdoxvSZpX58Sisqa/5ceYKeSnPFV458OlQV7KR5s34JBnZIhfxbzvzdez8MY5mqIwIIYdFLek3Y0laNWi61pWi8BBoxIP4nolfKAq8NUHxcz7e6X25BLzKiPEiV+yKWwmmjXkhKlZWyFTo8zoz0c7oyZtDc3okGUCNJZjn922qXSJZmF3GbWL+18TXmP22QL0xinQ+n9IaldLGuJuDMdUMTegIQ6shLm3umik0l0tWSGFVFieNlIji7wlp1re1ZFBlv08aSlgWv1oDeFOkQFINvX5eOJFnikFqOZcGE4o4oOoCKTZOEVEwiEHwFVmDpO2tYs0oinEYxS5GL3VX3/6jTEfivrF5dyyl9f7cMrc8sArR9oNLxtJ+M86AJ7m73/g7RdBpsk5D2WKk03rkHKZlg/9GZOBUkbvP1DCINg4l47L0Q8NqJP7RNl/o8mwo/Zoz2yZ6Dz492HoBgMcuIO6EfmEc="

  matrix:
    - LATEST=0 TERRAFORM_VERSION=0.12.18 TERRAFORM_SHA256SUM=e7ebe3ca988768bffe0c239d107645bd53515354cff6cbe5651718195a151700
    - LATEST=1 TERRAFORM_VERSION=0.11.14 TERRAFORM_SHA256SUM=9b9a4492738c69077b079e595f5b2a9ef1bc4e8fb5596610f69a6f322a8af8dd

script:
  - bash docker-build.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images
