name: Test and build
on: [push, pull_request]
jobs:
  test-and-build:
    name: '[Terraform ${{ matrix.build-jobs.terraform-version }}] test and build'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build-jobs:
          - terraform-version: "0.11.15"
            terraform-sha256sum: "e6c8c884de6c353cf98252c5e11faf972d4b30b5d070ab5ff70eaf92660a5aac"
            latest: 1
            experimental: false
          - terraform-version: "0.13.7"
            terraform-sha256sum: "4a52886e019b4fdad2439da5ff43388bbcc6cce9784fde32c53dcd0e28ca9957"
            latest: 0
            experimental: false
          - terraform-version: "1.0.6"
            terraform-sha256sum: "6a454323d252d34e928785a3b7c52bfaff1192f82685dfee4da1279bb700b733"
            latest: 0
            experimental: false
      
    continue-on-error: ${{ matrix.build-jobs.experimental }}

    env:
      LATEST: ${{ matrix.build-jobs.latest }}
      TERRAFORM_VERSION: ${{ matrix.build-jobs.terraform-version }}
      TERRAFROM_SHA256SUM: ${{ matrix.build-jobs.terraform-sha256sum }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: ./docker-build.sh
        shell: bash

      - name: Show build images
        run: docker images
        shell: bash

      - name: Push images
        run: ./docker-push.sh
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if:
          contains('
          refs/heads/master
          ', github.ref)

